include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
#obj-y := atmel_mxt_ts.o plugin_misc.o
obj-y := atmel_mxt_ts.o plugin_misc.o plugin_proci.o
#obj-y := plugin_misc.o
#obj-y := atmel_mxt_ts_mtk_interface.o
