include $(srctree)/drivers/misc/mediatek/Makefile.custom

# In case the platform does NOT support this type of sensors
obj-y   +=  gyroscope.o gyro_factory.o

obj-$(CONFIG_MTK_BMI160_GYRO)   +=  bmi160_gyro/
