include $(srctree)/drivers/misc/mediatek/Makefile.custom

# In case the platform does NOT support this type of sensors
obj-y   +=  alsps.o
obj-y   +=  alsps_factory.o
obj-y   +=  aal_control.o

obj-$(CONFIG_MTK_STK3X1X_DRIVER)+=  stk3x1x_driver/
obj-$(CONFIG_MTK_LTR559)	+=  ltr559/
