include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_ARCH_MT8163) += $(MTK_PLATFORM)/ 
obj-$(CONFIG_ARCH_MT6752) += $(MTK_PLATFORM)/ 
obj-$(CONFIG_ARCH_MT6795) += $(MTK_PLATFORM)/ 
obj-$(CONFIG_ARCH_MT6735) += $(MTK_PLATFORM)/ 
obj-$(CONFIG_ARCH_MT6735M) += $(MTK_PLATFORM)/
obj-$(CONFIG_ARCH_MT6753) += $(MTK_PLATFORM)/ 
obj-$(CONFIG_ARCH_MT6580) += $(MTK_PLATFORM)/ 
