include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/bmi160_acc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/step_counter
ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/include/linux

obj-y	:=  bmi160_stc.o

