include $(srctree)/drivers/misc/mediatek/Makefile.custom

# In case the platform does NOT support this type of sensors

obj-$(CONFIG_MTK_SCP_SENSORHUB) += SCP_sensorHub/
obj-$(CONFIG_MTK_SCP_SENSORHUB) += SCP_shf/
obj-$(CONFIG_INPUT_CWSTM32)	+= CwMcuSensor/
obj-$(CONFIG_MTK_ICM30628)	+= icm30628/
