include $(srctree)/drivers/misc/mediatek/Makefile.custom

# In case the platform does NOT support this type of sensors
obj-y   +=  barometer.o barometer_factory.o

obj-$(CONFIG_MTK_BMP180) += BMP180/
obj-$(CONFIG_MTK_BMP180_NEW) += BMP180-new/
obj-$(CONFIG_MTK_MS5607) += ms5607/
