include $(srctree)/drivers/misc/mediatek/Makefile.custom

# In case the platform does NOT support this type of sensors
obj-y   +=  mag.o
obj-y   +=  mag_factory.o

obj-$(CONFIG_MTK_AKM09911)   +=  akm09911/
obj-$(CONFIG_MTK_AKM09911_NEW)   +=  akm09911-new/
obj-$(CONFIG_MTK_YAS537)	+=  yamaha537/
