obj-$(CONFIG_MT_SCHED)=mt_sched.o mt_compat_sched.o 
#KVERSION=$(shell uname -r)
#all:
#	make -C /lib/modules/$(KVERSION)/build M=$(PWD) modules
#clean:
#	make -C /lib/modules/$(KVERSION)/build M=$(PWD) clean
