include $(srctree)/drivers/misc/mediatek/Makefile.custom
include $(srctree)/drivers/misc/mediatek/gud/Makefile.include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/mach/$(MTK_PLATFORM)/include/trustzone/m4u

ccflags-y += -I$(srctree)/drivers/misc/mediatek/m4u/$(MTK_PLATFORM)

obj-y += m4u.o m4u_mva.o m4u_pgtable.o m4u_debug.o
