################################################################################
# FrameBuffer Driver for Display
#
#
################################################################################

######################################
# MT6572/82/92 are lagecy projects, will be removed, so have no common part
# any more. Use belows for all when legacy projects are removed
# obj-$(CONFIG_MTK_FB) += common/
obj-$(CONFIG_MTK_FB) += $(subst ",,$(CONFIG_MTK_PLATFORM))/

obj-$(CONFIG_ARCH_MT6595) += common/
obj-$(CONFIG_ARCH_MT6752) += common/
obj-$(CONFIG_ARCH_MT6795) += common/
obj-$(CONFIG_ARCH_MT6735) += common/
obj-$(CONFIG_ARCH_MT6735M) += common/
obj-$(CONFIG_ARCH_MT6753) += common/
obj-$(CONFIG_ARCH_MT6580) += common/
obj-$(CONFIG_ARCH_MT6755) += common/

