include $(srctree)/drivers/misc/mediatek/Makefile.custom

# In case the platform does NOT support this type of sensors

obj-y   +=  accel.o accel_factory.o

obj-$(CONFIG_MTK_BMI160_ACC)   +=  bmi160_acc/

