
obj-y += $(subst ",,$(CONFIG_MTK_PLATFORM))/

obj-$(CONFIG_ARCH_MT6572) += 1.0/
obj-$(CONFIG_ARCH_MT6582) += 1.0/
obj-$(CONFIG_ARCH_MT6592) += 1.0/
obj-$(CONFIG_ARCH_MT6795) += 2.0/
obj-$(CONFIG_ARCH_MT6752) += 2.0/
obj-$(CONFIG_ARCH_MT6580) += 2.0/