#include "icm30628.h"

#ifdef MTK_PLATFORM

#include <linux/sensors_io.h>
void init_factory_node(void);

#else

#define ICM30628_FACTORY_IOCTL_GROUP                  0x20
#define GSENSOR_IOCTL_READ_SENSORDATA 				_IO(ICM30628_FACTORY_IOCTL_GROUP, 1)
#define GSENSOR_IOCTL_CLR_CALI						_IO(ICM30628_FACTORY_IOCTL_GROUP, 2)
#define GSENSOR_IOCTL_SET_CALI						_IO(ICM30628_FACTORY_IOCTL_GROUP, 3)
#define GSENSOR_IOCTL_GET_CALI						_IO(ICM30628_FACTORY_IOCTL_GROUP, 4)
#define GYROSCOPE_IOCTL_READ_SENSORDATA			_IO(ICM30628_FACTORY_IOCTL_GROUP, 5)
#define GYROSCOPE_IOCTL_CLR_CALI						_IO(ICM30628_FACTORY_IOCTL_GROUP, 6)
#define GYROSCOPE_IOCTL_SET_CALI						_IO(ICM30628_FACTORY_IOCTL_GROUP, 7)
#define GYROSCOPE_IOCTL_GET_CALI						_IO(ICM30628_FACTORY_IOCTL_GROUP, 8)
#define MSENSOR_IOCTL_READ_FACTORY_SENSORDATA	_IO(ICM30628_FACTORY_IOCTL_GROUP, 9)
#define MSENSOR_IOCTL_READ_SENSORDATA				_IO(ICM30628_FACTORY_IOCTL_GROUP, 10)
#define ALSPS_SET_PS_MODE								_IO(ICM30628_FACTORY_IOCTL_GROUP, 11)
#define ALSPS_SET_ALS_MODE							_IO(ICM30628_FACTORY_IOCTL_GROUP, 12)
#define ALSPS_GET_ALS_RAW_DATA						_IO(ICM30628_FACTORY_IOCTL_GROUP, 13)
#define ALSPS_GET_PS_RAW_DATA						_IO(ICM30628_FACTORY_IOCTL_GROUP, 14)
#define BAROMETER_GET_TEMP_DATA						_IO(ICM30628_FACTORY_IOCTL_GROUP, 15)
#define BAROMETER_GET_PRESS_DATA					_IO(ICM30628_FACTORY_IOCTL_GROUP, 16)
#define HRM_READ_SENSOR_DATA							_IO(ICM30628_FACTORY_IOCTL_GROUP, 17)

#endif