
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += icm30628.o icm30628_common.o icm30628_spi.o icm30628_math.o icm30628_debug.o icm30628_interrupt.o icm30628_power.o icm30628_factory.o
